version: '3.7'

services:

  server:
    image: ehtishamEjaz/node-app:v1.1
    container_name: express
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=mongodb+srv://Ehtisham_Mern:ehtisham123@cluster0.n3fsc.mongodb.net/?retryWrites=true&w=majority;

  client:
    stdin_open: true
    image: ehtishamEjaz/react-app:v1.1
    container_name: react
    volumes:
      - ./client/:/app
      - /app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"



